### ISSUE TITLE
Class path maybe wrong?

### ISSUE THREAD

**Issue by bergischweb** [medienreaktor/form_double_opt_in#1]
With TYPO3 8.7 I get error messages like `Medienreaktor\FormDoubleoptin\Controller\FormDoubleOptInController is not found`. They disappeared after renaming the class path from `FormDoubleOptIn` to `FormDoubleoptin` in all files. The naming conventions in Extbase are IMHO that the extension directory is changed to CamelCase: `form_doubleoptin` -> `FormDoubleoptin`.

**Comment by bergischweb** [comment]
You updated to V1.1.2 in the meantime, I observed the error with V 1.1.1

**Comment by danielkestler** [comment]
Thank you nonetheless. This is fixed indeed.
