### ISSUE TITLE
Avoid deprecated SignalSlot Dispatcher and use PSR-14 Events instead

### ISSUE THREAD

**Issue by simonschaufi** [medienreaktor/form_double_opt_in#6]
See:
- https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Hooks/EventDispatcher/Index.html
- https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Feature-88770-PSR-14BasedEventDispatcher.html

**Comment by danielkestler** [comment]
https://github.com/medienreaktor/form_double_opt_in/commit/a667843e9146cc945a8f395f1166ea54b506e9ed

**Comment by simonschaufi** [comment]
Thank you for the quick implementation. You can actually leave out the `injectEventDispatcher` method and `eventDispatcher` property as they exist in the `ActionController` already.

**Comment by danielkestler** [comment]
Ah, thanks, didn't know that. But that is only true for the ```ActionController```, right? I need the injection in the form finisher?

**Comment by simonschaufi** [comment]
Yes, only the controller. If you use phpstorm you should see that the method and prop is overwritten
