### ISSUE TITLE
Replace txt file ending with typoscript

### ISSUE THREAD

**Issue by simonschaufi** [medienreaktor/form_double_opt_in#7]
`setup.txt` and `constants.txt` are deprecated since a long time. Please use `.typoscript` file extension. Same applies for `ext_typoscript_setup.txt`

**Comment by danielkestler** [comment]
Thank you, closed. https://github.com/medienreaktor/form_double_opt_in/commit/543797a2de07a3a82fc3ede2c9b686c980f2dd79
